import Head from "next/head";
import SimulatorComponent from "components/simulator/Simulator";
export default function Simulator() {
    return (
        <div>
            <Head>
                <title>Simulator</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logoPurpleSaturated.png" />
            </Head>
            <main>
                <SimulatorComponent/>
            </main>
        </div>
    );
}
