import Head from "next/head";
import Nav from "components/achievements/nav/Nav";
import StatsBoard from "components/achievements/StatsBoard/StatsBoard";

export default function Achievements() {
    return (
        <div>
            <Head>
                <title>Achievements</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logoPurpleSaturated.png" />
            </Head>
            <main>
                <Nav />
                <StatsBoard />
            </main>
        </div>
    );
}
