import Head from 'next/head'

export default function Achievements() {
    return (
        <div>
            <Head>
                <title>Achievements</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

            </main>
        </div>
    )
}
