import AchievementsSection from 'components/home/achievements/AchievementsSection'
import ChoiceSection from 'components/home/choiceSection/ChoiceSection'
import Head from 'next/head'
import Hero from '../components/home/hero/Hero'

export default function Home() {
    return (
        <div>
            <Head>
                <title>recycleToearn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Hero />
                <ChoiceSection />
                <AchievementsSection />
            </main>
        </div>
    )
}
