import AchievementsSection from 'components/home/achievements/AchievementsSection'
import DarkSection from 'components/home/darkSection/darkSection'
import Hero from 'components/home/hero/Hero'
import Nav from 'components/shared/nav/Nav'
import Head from 'next/head'
import CoinInfo from '../components/home/coinInfo/CoinInfo'

/* 
@media(max-width: 1280px) {
@media(max-width: 768px) {
*/
export default function Home() {
    return (
        <div>
            <Head>
                <title>recycleToearn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav />
                <Hero />
                <CoinInfo />
                <DarkSection />
                <AchievementsSection />
            </main>
        </div>
    )
}
